### ISSUE TITLE
ERROR! the role 'postgresql' was not found in /Users/.../cspace-installer/roles:/Users/.../cspace-installer/roles:/Users/.../cspace-installer

### ISSUE THREAD

**Issue by pbelouin** [collectionspace/cspace-installer#11]
I seem to have mismatched users in the yaml files, but I have to admit that I'm quite a n00b with ansible - is there something I'm doing wrong? attached is my deploy.yml file - apologies if this is the wrong place to mention this issue!

**Comment by mark-cooper** [comment]
HI @pbelouin, I don't see an attached file. Can you try reuploading?

**Comment by mark-cooper** [comment]
But going by the error message I think you need to download the roles first: `ansible-galaxy install -r requirements.yml --force`.

**Comment by pbelouin** [comment]
Hi Mark, thank you for having a look at my issue - I just realised that yml files are not supported by github uploads - I've pasted it below instead:

But in any case I'll have a look at your suggesting above, thank you!

`---

# Email address to receive certbot notifications
certbot_admin_email: pbelouin@mpiwg-berlin.mpg.de

# SSL certs: uncomment this variable and leave it as an empty list
# to prevent SSL cert generation. This is generally only recommended
# for testing with IP addresses (no DNS configured)
# certbot_certs: []

# Password for the csadmin database user (update this and keep it SECRET!)
collectionspace_csadmin_password: teehee

# Setting this to true will trigger build steps
# irrespective of other tasks status
collectionspace_force_build: False

# IP address or domain name of the server added to DNS
# (latter can be used by certbot to generate an SSL cert)
collectionspace_addr: viz-heavens-map.mpiwg-berlin.mpg.de

# The CollectionSpace tenant that will be enabled and accessible online
collectionspace_tenant: core

#####
##### SECURITY - SETTINGS ONLY APPLY WHEN security.yml IS RUN
#####

# Mode for root user login, options:
# - "no" # disable root user ssh. Note: the quotes are required
# - prohibit-password # key only, password not allowed
# Warning: with permit_root_login = "no" ensure there is a user
# account available on the system for SSH access
permit_root_login: 'prohibit-password'

# List of ip addresses for SSH
# We recommend using an explicit list of known and trusted IP addresses
ssh_allowed_ip_addresses:
  # - "{{ lookup('url', 'http://checkip.amazonaws.com', split_lines=False) | replace('\n', '') }}"
  - 0.0.0.0/0 # all

# List of users to create on the server (default: none). Not
# creating users and permit_root_login = "no" can prevent SSH access
# so ensure that at least 1 user account exists for SSH access on
# the server and / or set permit_root_login = "prohibit-password".
# Note: users created this way have passwordless sudo privileges
# (i.e. it's a root like account)
users: 
  - name: pbelouin
    shell: bin/bash
    # Example resolves to: /path/to/$USERNAME/.ssh/id_rsa.pub on local machine
    public_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
`
