### ISSUE TITLE
Tomcat issue after successful installation

### ISSUE THREAD

**Issue by pbelouin** [collectionspace/cspace-installer#12]
Based on Mark's feedback, I have successfully run the ansible playbook; The output is as follows:

<img width="1513" alt="Screenshot 2020-12-08 at 18 33 54" src="https://user-images.githubusercontent.com/224437/101519973-1d00f380-3984-11eb-8b59-33bedebf4cad.png">

However, when visiting the server's IP address, I get redirected to /cspace/core/login, and get the following error from Tomcat:

<img width="1744" alt="Screenshot 2020-12-08 at 18 33 35" src="https://user-images.githubusercontent.com/224437/101520057-3a35c200-3984-11eb-8457-7dc71bdc4111.png">

Is there something I'm not doing properly perhaps? I have disabled certbot, but this doesn't seem to be the issue 🤔

**Comment by pbelouin** [comment]
As I keep digging by running systemd on the remote machine, it seems that the service instance is running properly:

<img width="1233" alt="Screenshot 2020-12-09 at 12 59 37" src="https://user-images.githubusercontent.com/224437/101627383-95b48e00-3a1e-11eb-9373-16210ea7552a.png">

**Comment by mark-cooper** [comment]
Hi @pbelouin, sorry for the slow response. 

It looks like the UI for the core tenant hasn't deployed. Can you paste the contents of your config file here?

Also, you can look into the log files: https://github.com/collectionspace/cspace-installer/blob/master/docs/SYSTEM.md#collectionspace -- to see if there's an obvious error.

Did you try restarting the server? `service collectionspace restart` (then tail the logs)

Did the databases get created? In particular look for the content database as that gets created as the server starts up: https://github.com/collectionspace/cspace-installer/blob/master/docs/SYSTEM.md#connecting-to-postgres

There may have been an error in the build process which you can re-attempt by setting: `collectionspace_force_build: True`

Did Ansible fail part way through? If so you could try starting over in case something failed that the installer wasn't able to recover from. The installer has been tested multiple times recently and worked successfully each time, except in one instance (an under resourced server, 2gb of ram is the absolute minimum, 4gb of ram is recommended).

**Comment by pbelouin** [comment]
Dear Mark, no worries really, I can imagine you must be pretty busy! You gave me a lot of pointers to try out, I will give all of this a go and hopefully will get it running! I will report back in any case 👍

**Comment by pbelouin** [comment]
Dear Mark,

Forcing the build did the trick! I'll keep the issue open just a little longer, to make sure everything's hunky-dory. Thanks again for the exhaustive answer!
