### ISSUE TITLE
Unable to restart service nginx

### ISSUE THREAD

**Issue by mojumah** [collectionspace/cspace-installer#15]
after running the command `ansible-playbook -i $DOMAIN, collectionspace.yml -u $USER -e @vars/deploy.yml`
I get the error
`Unable to restart service nginx: Job for nginx.service failed because the control process exited with error code.`
I am installing Collection Space using Ansible on Ubuntu 18.04

**Comment by mark-cooper** [comment]
Closing because recent testing has not found any issues with nginx. Please re-open if you feel this needs to be looked into further.
