### ISSUE TITLE
Certificate generation fails for Ubuntu 20.04

### ISSUE THREAD

**Issue by mikejritter** [collectionspace/cspace-installer#9]
When running the installer on the latest LTS version of Ubuntu, the step for generating an https certificate will fail with the error `python-virtualenv has no installation candidate`. This is caused by changes Ubuntu made to its python installation conflicting with certbot (see: https://github.com/certbot/certbot/issues/7941) and will likely need an update from `ansible-role-certbot`: https://github.com/geerlingguy/ansible-role-certbot/issues/132.

**Comment by mark-cooper** [comment]
https://github.com/geerlingguy/ansible-role-certbot/issues/134

**Comment by mark-cooper** [comment]
https://github.com/geerlingguy/ansible-role-certbot/pull/142/files
